import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";

const geistSans = Ubuntu({
  weight: "500"
});

export const metadata: Metadata = {
  title: "Persona Links",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
