import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/shared/theme-provider';
import { ScrollToTopButton } from '@/components/shared/ScrollTopButton';

const geistSans = Ubuntu({
    weight: '500',
});

export const metadata: Metadata = {
    title: 'Persona Links',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={`${geistSans} antialiased`}>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                    <ScrollToTopButton />
                </ThemeProvider>
            </body>
        </html>
    );
}
